### ISSUE TITLE
没看到有ng-zorro的组件使用呢？

### ISSUE THREAD

**Issue by justein** [hzlshen/ionic-cli#1]
很好的一个结合点，目前项目也打算基于ionic和AD来构建，请问Zorro的组件使用，能给个示例么？zorro的样式用的less，而ionic是sass，这块要怎么匹配呢？

**Comment by hzlshen** [comment]
zorro好像有sass版的，不过 zorro一般都是用来做后台系统的 放在ionic里似乎不太合适
